trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfigueartion: 'Release'

steps:
  - task: UseDotNet@2
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'